name: Build executables

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Build Windows exe
        run: pyinstaller --onefile --windowed --name MyApp main.py
        shell: bash

      - name: Upload exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/MyApp.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build Mac .app
        run: |
          pyinstaller --windowed --name MyApp main.py
          ls dist

      - name: Upload Mac app
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/MyApp.app
